---
- name: Create /var/lib/yake directory
  become: true
  ansible.builtin.file:
    path: /var/lib/yake
    owner: "{{ flux_install_uid }}"
    group: "{{ flux_install_gid }}"
    mode: 0755
    state: directory

- name: Run flux container
  become: "{{ flux_install_become }}"
  community.docker.docker_container:
    name: flux
    command: sleep infinity
    image: "{{ flux_install_container_registry }}/{{ flux_install_container_image }}:{{ flux_install_container_tag }}"
    env:
      USER_ID: "{{ flux_install_uid }}"
      GROUP_ID: "{{ flux_install_gid }}"
    volumes:
      - /var/lib/yake:/var/lib/yake
    state: started

- name: Copy flux script
  become: true
  ansible.builtin.copy:
    src: flux
    dest: /usr/local/bin/flux
    mode: 0755
    owner: root
    group: root
