---
charts:
  - name: cilium
    # renovate: datasource=github-releases depName=cilium/cilium
    version: '1.17.0'
    repository:
      url: https://helm.cilium.io/
  - name: cert-manager
    # renovate: datasource=github-releases depName=cert-manager/cert-manager
    version: '1.17.1'
    repository:
      url: https://charts.jetstack.io
