---
charts:
  - name: cilium
    # renovate: datasource=github-releases depName=cilium/cilium
    version: '1.17.4'
    repository:
      url: https://helm.cilium.io/
  - name: ingress-nginx
    # renovate: datasource=github-releases depName=kubernetes/ingress-nginx
    version: '4.12.2'
    repository:
      url: https://kubernetes.github.io/ingress-nginx
  - name: cert-manager
    # renovate: datasource=github-releases depName=cert-manager/cert-manager
    version: '1.17.2'
    repository:
      url: https://charts.jetstack.io
  - name: keycloak
    # renovate: datasource=docker depName=registry-1.docker.io/bitnamicharts/keycloak
    version: '24.7.3'
    repository:
      url: https://charts.bitnami.com/bitnami
