---
- name: Cleanup the whole setup
  hosts: all

  tasks:
    - name: Delete Garden cluster
      ansible.builtin.command: ./.local/yake-kubectl delete cluster garden
      environment:
        KUBECONFIG: /var/lib/yake/kubeconfig.clusterapi
      timeout: 600
      ignore_errors: true

    - name: Remove k3s
      ansible.builtin.command: /usr/local/bin/k3s-uninstall.sh
      ignore_errors: true
      become: true
      timeout: 300
      when: gardener_operator_keycloak_enabled | bool

    - name: Delete kind cluster
      ansible.builtin.command: "{{ playbook_dir }}/.local/yake-kind delete cluster --name clusterapi"
      timeout: 300

    - name: Include OpenStack cleanup
      include_tasks: openstack-cleanup.yml
      when: cleanup_clouds_file is file

    - name: List all containers
      community.docker.docker_host_info:
        containers: true
      register: docker_info

    - name: Remove all containers
      community.docker.docker_container:
        name: "{{ item }}"
        state: absent
        force_kill: true
      loop: "{{ docker_info.containers | default([]) | map(attribute='Id') | list }}"

    - name: Remove yake directory
      ansible.builtin.file:
        path: /var/lib/yake
        state: absent
      become: true
