---
- name: Install kubectl
  ansible.builtin.import_playbook: kubectl-install.yml

- name: Install helm
  ansible.builtin.import_playbook: helm-install.yml

- name: Install clusterctl
  ansible.builtin.import_playbook: clusterctl-install.yml

- name: Install kind
  ansible.builtin.import_playbook: kind-install.yml

- name: Create kind cluster
  ansible.builtin.import_playbook: kind-cluster.yml

- name: Install clusterapi
  ansible.builtin.import_playbook: clusterapi-install.yml

- name: Install clusterapi-cluster
  ansible.builtin.import_playbook: clusterapi-cluster.yml

- name: Install gardener-operator
  ansible.builtin.import_playbook: gardener-operator.yml
