---
- name: Install kubectl
  hosts: "{{ hosts_kubectl_install | d('all') }}"
  tags: [kubectl]
  roles:
    - role: kubectl_install

- name: Install helm
  hosts: "{{ hosts_helm_install | d('all') }}"
  tags: [helm]
  roles:
    - role: helm_install

- name: Install clusterctl
  hosts: "{{ hosts_clusterctl_install | d('all') }}"
  tags: [clusterctl]
  roles:
    - role: clusterctl_install

- name: Setup management cluster
  hosts: "{{ hosts_management_cluster | d('all') }}"
  tags: [management-cluster]
  roles:
    - role: management_cluster

- name: Install Cluster API
  hosts: "{{ hosts_clusterapi_install | d('all') }}"
  tags: [clusterapi]
  roles:
    - role: clusterapi_install

- name: Create garden cluster
  hosts: "{{ hosts_clusterapi_cluster | d('all') }}"
  tags: [garden-cluster]
  roles:
    - role: clusterapi_cluster

- name: Setup Gardener Operator
  hosts: "{{ hosts_gardener_operator | d('all') }}"
  tags: [gardener]
  roles:
    - role: gardener_operator
