ARG ALPINE_VERSION=3.24@sha256:5b02b42e375f7426f8d65c3af331ca05d9878f9989230354504e0b9dfd431f60
FROM alpine:${ALPINE_VERSION}

COPY --chmod=0755 entrypoint.sh /entrypoint.sh
ARG VERSION=v0.33.0  # renovate: datasource=github-releases depName=kubernetes-sigs/kind
ADD --chmod=0755 https://kind.sigs.k8s.io/dl/${VERSION}/kind-linux-amd64 /usr/bin/kind

ENV USER_NAME=kind
ENV USER_ID=1000
ENV GROUP_ID=1000

ENV DOCKER_GROUP_NAME=docker
ENV DOCKER_GROUP_ID=988

RUN apk update --no-cache \
    && apk upgrade --no-cache --available \
    && apk add --no-cache \
      docker-cli \
      dumb-init \
      shadow \
    && addgroup -g ${GROUP_ID} ${USER_NAME} \
    && addgroup -g ${DOCKER_GROUP_ID} ${DOCKER_GROUP_NAME} \
    && adduser -u ${USER_ID} -D -G ${USER_NAME} ${USER_NAME} \
    && usermod -aG ${DOCKER_GROUP_NAME} ${USER_NAME} \
    && mkdir //var/lib/yake \
    && chown -R ${USER_NAME}:${USER_NAME} /var/lib/yake

WORKDIR /var/lib/yake

VOLUME ["/var/lib/yake"]

ENTRYPOINT ["/entrypoint.sh"]
