---
- name: Fix docker wiping ipv6 default route
  become: true
  ansible.builtin.shell: |
    set -e
    set -x

    INTERFACE=$(ip -6 route show default | awk '{for(i=1;i<=NF;i++) if($i=="dev") print $(i+1)}' | head -n 1)
    sysctl -w net.ipv6.conf.$INTERFACE.accept_ra=2
  changed_when: false
  args:
    executable: /bin/bash

- name: Ensure docker
  ansible.builtin.include_role:
    name: osism.services.docker
  vars:
    docker_user: zuul
    docker_group: zuul
    docker_python_install: false

- name: Ensure kind
  ansible.builtin.include_role:
    name: kind_install
  vars:
    kind_install_become: true

- name: Ensure kubectl
  ansible.builtin.include_role:
    name: kubectl_install
  vars:
    kubectl_install_become: true

- name: Reset connection
  ansible.builtin.meta: reset_connection
