---
- name: Copy kind cluster configuration file
  become: true
  ansible.builtin.template:
    src: config.yml.j2
    dest: "/var/lib/yake/config.{{ kind_cluster_name }}.yml"
    mode: 0644
    owner: "{{ kind_cluster_uid }}"
    group: "{{ kind_cluster_gid }}"

- name: Pull kind container image
  become: "{{ kind_cluster_become }}"
  community.docker.docker_image:
    name: "{{ kind_cluster_image }}"
    source: pull

- name: Check if the kind cluster exists
  become: "{{ kind_cluster_become }}"
  ansible.builtin.command: "{{ playbook_dir }}/.local/yake-kind get clusters"
  register: kind_clusters # noqa: var-naming[no-role-prefix]
  changed_when: false

- name: Prepare kind create command
  ansible.builtin.set_fact:
    _kind_create_cluster: "{{ playbook_dir }}/.local/yake-kind create cluster --name {{ kind_cluster_name }} --image {{ kind_cluster_image }} --kubeconfig {{ kind_cluster_kubeconfig }} --config /var/lib/yake/config.{{ kind_cluster_name }}.yml" # noqa: var-naming[no-role-prefix]

- name: Print kind create command
  ansible.builtin.debug:
    var: _kind_create_cluster

- name: Create kind cluster
  become: "{{ kind_cluster_become }}"
  ansible.builtin.shell: "{{ _kind_create_cluster }}"
  args:
    executable: /bin/bash
  register: result # noqa: var-naming[no-role-prefix]
  changed_when: "'Creating cluster' in result.stdout"
  when:
    - "kind_cluster_state == 'present'"
    - "kind_cluster_name not in kind_clusters.stdout_lines"
  async: 180
  poll: 5

- name: Wait for kind cluster to be ready
  become: "{{ kind_cluster_become }}"
  ansible.builtin.command: >
    {{ playbook_dir }}/.local/yake-kubectl --kubeconfig {{ kind_cluster_kubeconfig }} wait --for=condition=Ready nodes --all --timeout=300s
  register: wait_result # noqa: var-naming[no-role-prefix]
  until: wait_result.rc == 0
  retries: 10
  delay: 10
  when:
    - "kind_cluster_state == 'present'"
    - "kind_cluster_name not in kind_clusters.stdout_lines"
  changed_when: false

- name: Change permissions of kubeconfig
  become: true
  ansible.builtin.file:
    path: "/var/lib/yake/kubeconfig.{{ kind_cluster_name }}"
    mode: 0640
    owner: "{{ kind_cluster_uid }}"
    group: "{{ kind_cluster_gid }}"

- name: Copy kubeconfig
  become: true
  ansible.builtin.copy:
    src: "/var/lib/yake/kubeconfig.{{ kind_cluster_name }}"
    dest: "/var/lib/yake/kubeconfig"
    mode: 0640
    owner: "{{ kind_cluster_uid }}"
    group: "{{ kind_cluster_gid }}"
  when: kind_cluster_primary == kind_cluster_name
