ARG ALPINE_VERSION=3.23@sha256:865b95f46d98cf867a156fe4a135ad3fe50d2056aa3f25ed31662dff6da4eb62
FROM alpine:${ALPINE_VERSION}

COPY --chmod=0755 entrypoint.sh /entrypoint.sh
ARG VERSION=v1.33.7  # renovate: datasource=github-releases depName=kubernetes/kubernetes
ADD --chmod=0755 https://dl.k8s.io/release/${VERSION}/bin/linux/amd64/kubectl /usr/bin/kubectl

ENV USER_NAME=kubectl
ENV USER_ID=1000
ENV GROUP_ID=1000

RUN apk update --no-cache \
    && apk upgrade --no-cache --available \
    && apk add --no-cache \
      dumb-init \
      shadow \
    && addgroup -g ${GROUP_ID} ${USER_NAME} \
    && adduser -u ${USER_ID} -D -G ${USER_NAME} ${USER_NAME} \
    && mkdir /var/lib/yake \
    && chown -R ${USER_NAME}:${USER_NAME} /var/lib/yake

WORKDIR /var/lib/yake

VOLUME ["/var/lib/yake"]

ENTRYPOINT ["/entrypoint.sh"]
