ARG ALPINE_VERSION=3.21
FROM alpine:${ALPINE_VERSION}

COPY --chmod=0755 entrypoint.sh /entrypoint.sh
ARG KUBECTL_VERSION=v1.32.0
ADD --chmod=0755 https://dl.k8s.io/release/${KUBECTL_VERSION}/bin/linux/amd64/kubectl /usr/bin/kubectl

ENV USER_NAME=kubectl
ENV USER_ID=1000
ENV GROUP_ID=1000

RUN apk update --no-cache \
    && apk upgrade --no-cache --available \
    && apk add --no-cache \
      dumb-init \
      shadow \
    && addgroup -g ${GROUP_ID} ${USER_NAME} \
    && adduser -u ${USER_ID} -D -G ${USER_NAME} ${USER_NAME} \
    && mkdir /${USER_NAME} \
    && chown -R ${USER_NAME}:${USER_NAME} /${USER_NAME}

USER ${USER_NAME}
WORKDIR /{$USER_NAME}

VOLUME ["/${USER_NAME}"]

ENTRYPOINT ["/entrypoint.sh"]
