---
- name: Copy clouds.yaml file
  ansible.builtin.template:
    src: clouds.yaml.j2
    dest: "/var/lib/yake/clouds.{{ clusterapi_cluster_name }}.yaml"
    owner: "{{ clusterapi_cluster_uid }}"
    group: "{{ clusterapi_cluster_gid }}"
    mode: 0644

- name: Slurp clouds.yaml file
  ansible.builtin.slurp:
    src: "/var/lib/yake/clouds.{{ clusterapi_cluster_name }}.yaml"
  register: result_clouds_yaml

- name: Set _clusterapi_cluster_cloud_yaml_b64 fact
  ansible.builtin.set_fact:
    _clusterapi_cluster_cloud_yaml_b64: "{{ result_clouds_yaml.content }}"

- name: Copy cluster template file
  ansible.builtin.copy:
    src: cluster-template.yaml
    dest: /var/lib/yake/cluster-template.yaml
    owner: "{{ clusterapi_cluster_uid }}"
    group: "{{ clusterapi_cluster_gid }}"
    mode: 0644

- name: Create ssh keypair
  openstack.cloud.keypair:
    cloud: "{{ clusterapi_cluster_openstack_cloud }}"
    state: present
    name: "{{ clusterapi_cluster_ssh_key_name }}"
  register: result_keypair

- name: Write private ssh key
  ansible.builtin.copy:
    content: "{{ result_keypair.keypair.private_key }}"
    dest: "/var/lib/yake/id_rsa.{{ clusterapi_cluster_name }}"
    owner: "{{ clusterapi_cluster_uid }}"
    group: "{{ clusterapi_cluster_gid }}"
    mode: 0644
  when: result_keypair.changed  # noqa no-handler

- name: Write public ssh key
  ansible.builtin.copy:
    content: "{{ result_keypair.keypair.public_key }}"
    dest: "/var/lib/yake/id_rsa.{{ clusterapi_cluster_name }}.pub"
    owner: "{{ clusterapi_cluster_uid }}"
    group: "{{ clusterapi_cluster_gid }}"
    mode: 0644
  when: result_keypair.changed  # noqa no-handler

- name: Get external network ID
  openstack.cloud.networks_info:
    name: "{{ clusterapi_cluster_external_network }}"
  register: result_external_network

- name: Set _clusterapi_cluster_external_network fact
  ansible.builtin.set_fact:
    _clusterapi_cluster_external_network: "{{ result_external_network.networks | first | default({}) }}"

- name: Set _clusterapi_cluster_external_network_id fact
  ansible.builtin.set_fact:
    _clusterapi_cluster_external_network_id: "{{ _clusterapi_cluster_external_network.id | default('') }}"

- name: Combine clusterapi_cluster_defaults and clusterapi_cluster_extra
  ansible.builtin.set_fact:
    _clusterapi_cluster: "{{ clusterapi_cluster_defaults | combine(clusterapi_cluster_extra) }}"

- name: Copy cluster configuration file
  ansible.builtin.template:
    src: config.yaml.j2
    dest: "/var/lib/yake/config.{{ clusterapi_cluster_name }}.yaml"
    owner: "{{ clusterapi_cluster_uid }}"
    group: "{{ clusterapi_cluster_gid }}"
    mode: 0644

- name: Generate manifest to create Kubernetes cluster
  become: "{{ clusterapi_cluster_become }}"
  ansible.builtin.shell: |
    /usr/local/bin/clusterctl --config /var/lib/yake/config.{{ clusterapi_cluster_name }}.yaml generate cluster --from /var/lib/yake/cluster-template.yaml {{ clusterapi_cluster_name }} > /var/lib/yake/cluster.{{ clusterapi_cluster_name }}.yaml
  args:
    executable: /bin/bash
  changed_when: false

- name: Create Kubernetes cluster
  kubernetes.core.k8s:
    kubeconfig: "/var/lib/yake/kubeconfig.{{ clusterapi_cluster_kind_cluster_name }}"
    state: present
    wait: true
    src: "/var/lib/yake/cluster.{{ clusterapi_cluster_name }}.yaml"

- name: Get kubeconfig
  ansible.builtin.command: "clusterctl get kubeconfig {{ clusterapi_cluster_name }}"
  register: result_kubeconfig
  changed_when: false
  until: result_kubeconfig.rc == 0
  retries: 30
  delay: 10

- name: Write kubeconfig
  ansible.builtin.copy:
    content: "{{ result_kubeconfig.stdout }}"
    dest: "/var/lib/yake/kubeconfig.{{ clusterapi_cluster_name }}"
    owner: "{{ clusterapi_cluster_uid }}"
    group: "{{ clusterapi_cluster_gid }}"
    mode: 0644

- name: Wait for Kubernetes API
  kubernetes.core.k8s_info:
    kubeconfig: "/var/lib/yake/kubeconfig.{{ clusterapi_cluster_name }}"
    kind: Node
  register: result_k8s_nodes
  until: result_k8s_nodes.resources is defined
  retries: 60
  delay: 10

- name: Copy calico manifet
  ansible.builtin.copy:
    src: calico.yaml
    dest: /var/lib/yake/calico.yaml
    owner: "{{ clusterapi_cluster_uid }}"
    group: "{{ clusterapi_cluster_gid }}"
    mode: 0644

- name: Apply calico manifest
  kubernetes.core.k8s:
    kubeconfig: "/var/lib/yake/kubeconfig.{{ clusterapi_cluster_name }}"
    state: present
    src: /var/lib/yake/calico.yaml

- name: Wait for calico-node pods
  kubernetes.core.k8s_info:
    kubeconfig: "/var/lib/yake/kubeconfig.{{ clusterapi_cluster_name }}"
    kind: Pod
    namespace: kube-system
  register: calico_pods
  until: >
    calico_pods.resources is defined and
    (
      calico_pods.resources
      | selectattr('metadata.labels', 'defined')
      | selectattr('metadata.labels.k8s-app', 'defined')
      | selectattr('metadata.labels.k8s-app', 'equalto', 'calico-node')
      | selectattr('status.phase', 'equalto', 'Running')
      | list | length ==
      calico_pods.resources
      | selectattr('metadata.labels', 'defined')
      | selectattr('metadata.labels.k8s-app', 'defined')
      | selectattr('metadata.labels.k8s-app', 'equalto', 'calico-node')
      | list | length
    )
  retries: 30
  delay: 10

- name: Copy cloud.conf file
  ansible.builtin.template:
    src: cloud.conf.j2
    dest: "/var/lib/yake/cloud.{{ clusterapi_cluster_name }}.conf"
    owner: "{{ clusterapi_cluster_uid }}"
    group: "{{ clusterapi_cluster_gid }}"
    mode: 0644

- name: Slurp cloud.conf file
  ansible.builtin.slurp:
    src: "/var/lib/yake/cloud.{{ clusterapi_cluster_name }}.conf"
  register: register_cloud_conf

- name: Create cloud-config secret
  kubernetes.core.k8s:
    kubeconfig: "/var/lib/yake/kubeconfig.{{ clusterapi_cluster_name }}"
    state: present
    wait: true
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: cloud-config
        namespace: kube-system
      type: Opaque
      stringData:
        cloud.conf: "{{ register_cloud_conf.content | b64decode }}"

- name: Copy CCM manifests
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "/var/lib/yake/{{ item }}"
    owner: "{{ clusterapi_cluster_uid }}"
    group: "{{ clusterapi_cluster_gid }}"
    mode: 0644
  loop:
    - cloud-controller-manager-role-bindings.yaml
    - cloud-controller-manager-roles.yaml
    - openstack-cloud-controller-manager-ds.yaml

- name: Apply CCM manifests
  kubernetes.core.k8s:
    kubeconfig: "/var/lib/yake/kubeconfig.{{ clusterapi_cluster_name }}"
    state: present
    src: "/var/lib/yake/{{ item }}"
  loop:
    - cloud-controller-manager-role-bindings.yaml
    - cloud-controller-manager-roles.yaml
    - openstack-cloud-controller-manager-ds.yaml

- name: Wait for coredns pods
  kubernetes.core.k8s_info:
    kubeconfig: "/var/lib/yake/kubeconfig.{{ clusterapi_cluster_name }}"
    kind: Pod
    namespace: kube-system
  register: coredns_pods
  until: >
    coredns_pods.resources is defined and
    (
      coredns_pods.resources
      | selectattr('metadata.labels', 'defined')
      | selectattr('metadata.labels.k8s-app', 'defined')
      | selectattr('metadata.labels.k8s-app', 'equalto', 'kube-dns')
      | selectattr('status.phase', 'equalto', 'Running')
      | list | length ==
      coredns_pods.resources
      | selectattr('metadata.labels', 'defined')
      | selectattr('metadata.labels.k8s-app', 'defined')
      | selectattr('metadata.labels.k8s-app', 'equalto', 'kube-dns')
      | list | length
    )
  retries: 30
  delay: 10

- name: Copy CSI manifests
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "/var/lib/yake/{{ item }}"
    owner: "{{ clusterapi_cluster_uid }}"
    group: "{{ clusterapi_cluster_gid }}"
    mode: 0644
  loop:
    - cinder-csi-controllerplugin-rbac.yaml
    - cinder-csi-controllerplugin.yaml
    - cinder-csi-nodeplugin-rbac.yaml
    - cinder-csi-nodeplugin.yaml
    - csi-cinder-driver.yaml
    - csi-secret-cinderplugin.yaml

- name: Apply CSI manifests
  kubernetes.core.k8s:
    kubeconfig: "/var/lib/yake/kubeconfig.{{ clusterapi_cluster_name }}"
    state: present
    src: "/var/lib/yake/{{ item }}"
  loop:
    - cinder-csi-controllerplugin-rbac.yaml
    - cinder-csi-controllerplugin.yaml
    - cinder-csi-nodeplugin-rbac.yaml
    - cinder-csi-nodeplugin.yaml
    - csi-cinder-driver.yaml
    - csi-secret-cinderplugin.yaml

- name: Wait for CSI pods
  kubernetes.core.k8s_info:
    kubeconfig: "/var/lib/yake/kubeconfig.{{ clusterapi_cluster_name }}"
    kind: Pod
    namespace: kube-system
  register: csi_pods
  until: >
    csi_pods.resources is defined and
    (
      csi_pods.resources
      | selectattr('metadata.labels', 'defined')
      | selectattr('metadata.labels.app', 'defined')
      | selectattr('metadata.labels.app', 'equalto', 'csi-cinder-nodeplugin')
      | selectattr('status.phase', 'equalto', 'Running')
      | list | length ==
      csi_pods.resources
      | selectattr('metadata.labels', 'defined')
      | selectattr('metadata.labels.app', 'defined')
      | selectattr('metadata.labels.app', 'equalto', 'csi-cinder-nodeplugin')
      | list | length
    )
  retries: 30
  delay: 10
