---
- name: Create /var/lib/yake directory
  become: true
  ansible.builtin.file:
    path: /var/lib/yake
    owner: "{{ clusterapi_cluster_uid }}"
    group: "{{ clusterapi_cluster_gid }}"
    mode: 0755
    state: directory

- name: Include create tasks
  ansible.builtin.include_tasks: create.yml
  when: clusterapi_cluster_state == "present"

- name: Include delete tasks
  ansible.builtin.include_tasks: delete.yml
  when: clusterapi_cluster_state == "absent"
