---
- name: Deploy calico
  kubernetes.core.helm:
    binary_path: "{{ playbook_dir }}/.local/yake-helm"
    release_name: calico
    chart_ref: tigera-operator
    chart_repo_url: https://docs.tigera.io/calico/charts
    chart_version: "{{ clusterapi_cluster_calico_version }}"
    release_namespace: tigera-operator
    create_namespace: true
    kubeconfig: "/var/lib/yake/kubeconfig.{{ clusterapi_cluster_name }}"
    wait: true
    values: "{{ clusterapi_cluster_calico_helm_values }}"
  environment: "{{ clusterapi_cluster_proxy_env }}"

- name: Wait for calico-node daemonset
  kubernetes.core.k8s_info:
    kubeconfig: "/var/lib/yake/kubeconfig.{{ clusterapi_cluster_name }}"
    kind: DaemonSet
    name: calico-node
    namespace: calico-system
    wait: true
    wait_timeout: 300
  register: result_network_daemonset  # noqa: var-naming[no-role-prefix]
  until: result_network_daemonset.resources | length > 0
  retries: 30
  delay: 10
