---
- name: Deploy calico
  kubernetes.core.helm:
    binary_path: "{{ playbook_dir }}/.local/yake-helm"
    release_name: calico
    chart_ref: tigera-operator
    chart_repo_url: https://docs.tigera.io/calico/charts
    chart_version: "{{ clusterapi_cluster_calico_version }}"
    release_namespace: tigera-operator
    create_namespace: true
    kubeconfig: "/var/lib/yake/kubeconfig.{{ clusterapi_cluster_name }}"
    wait: true
  environment: "{{ clusterapi_cluster_proxy_env }}"

- name: Wait for calico-node pods
  kubernetes.core.k8s_info:
    kubeconfig: "/var/lib/yake/kubeconfig.{{ clusterapi_cluster_name }}"
    kind: Pod
    namespace: calico-system
  register: calico_pods  # noqa: var-naming[no-role-prefix]
  until: >
    calico_pods.resources is defined and
    (
      calico_pods.resources
      | selectattr('metadata.labels', 'defined')
      | selectattr('metadata.labels.k8s-app', 'defined')
      | selectattr('metadata.labels.k8s-app', 'equalto', 'calico-node')
      | selectattr('status.phase', 'equalto', 'Running')
      | list | length ==
      calico_pods.resources
      | selectattr('metadata.labels', 'defined')
      | selectattr('metadata.labels.k8s-app', 'defined')
      | selectattr('metadata.labels.k8s-app', 'equalto', 'calico-node')
      | list | length
    )
  retries: 30
  delay: 10
