---
- name: Deploy cilium
  kubernetes.core.helm:
    binary_path: "{{ playbook_dir }}/.local/yake-helm"
    release_name: cilium
    chart_ref: oci://quay.io/cilium/charts/cilium
    chart_version: "{{ clusterapi_cluster_cilium_version }}"
    release_namespace: kube-system
    create_namespace: true
    kubeconfig: "/var/lib/yake/kubeconfig.{{ clusterapi_cluster_name }}"
    wait: true
    values: "{{ clusterapi_cluster_cilium_helm_values }}"
  environment: "{{ clusterapi_cluster_proxy_env }}"

- name: Wait for cilium daemonset
  kubernetes.core.k8s_info:
    kubeconfig: "/var/lib/yake/kubeconfig.{{ clusterapi_cluster_name }}"
    kind: DaemonSet
    name: cilium
    namespace: kube-system
    wait: true
    wait_timeout: 300
