---
galaxy_info:
  author: Marius Wernicke
  description: Role to install garden control plane with yake
  company: 23 Technologies GmbH
  license: Apache License 2.0
  min_ansible_version: 2.18.0
  platforms:
    - name: Ubuntu
      versions:
        - noble
  galaxy_tags:
    - kubernetes
    - helm
    - flux
dependencies: []
