ARG ALPINE_VERSION=3.23@sha256:25109184c71bdad752c8312a8623239686a9a2071e8825f20acb8f2198c3f659
FROM alpine:${ALPINE_VERSION}

COPY --chmod=0755 entrypoint.sh /entrypoint.sh
ARG VERSION=v3.20.0  # renovate: datasource=github-releases depName=helm/helm
ADD https://get.helm.sh/helm-${VERSION}-linux-amd64.tar.gz /helm.tar.gz

ENV USER_NAME=helm
ENV USER_ID=1000
ENV GROUP_ID=1000

RUN apk update --no-cache \
    && apk upgrade --no-cache --available \
    && apk add --no-cache \
      dumb-init \
      shadow \
    && addgroup -g ${GROUP_ID} ${USER_NAME} \
    && adduser -u ${USER_ID} -D -G ${USER_NAME} ${USER_NAME} \
    && mkdir //var/lib/yake \
    && chown -R ${USER_NAME}:${USER_NAME} /var/lib/yake \
    && tar -xzf /helm.tar.gz --strip-components=1 -C /usr/local/bin linux-amd64/helm \
    && rm /helm.tar.gz

WORKDIR /var/lib/yake

VOLUME ["/var/lib/yake"]

ENTRYPOINT ["/entrypoint.sh"]
