ARG ALPINE_VERSION=3.24@sha256:5b02b42e375f7426f8d65c3af331ca05d9878f9989230354504e0b9dfd431f60
FROM alpine:${ALPINE_VERSION}

COPY --chmod=0755 entrypoint.sh /entrypoint.sh
ARG VERSION=v3.22.0  # renovate: datasource=github-releases depName=helm/helm
ADD https://get.helm.sh/helm-${VERSION}-linux-amd64.tar.gz /helm.tar.gz

ENV USER_NAME=helm
ENV USER_ID=1000
ENV GROUP_ID=1000

RUN apk update --no-cache \
    && apk upgrade --no-cache --available \
    && apk add --no-cache \
      dumb-init \
      shadow \
    && addgroup -g ${GROUP_ID} ${USER_NAME} \
    && adduser -u ${USER_ID} -D -G ${USER_NAME} ${USER_NAME} \
    && mkdir //var/lib/yake \
    && chown -R ${USER_NAME}:${USER_NAME} /var/lib/yake \
    && tar -xzf /helm.tar.gz --strip-components=1 -C /usr/local/bin linux-amd64/helm \
    && rm /helm.tar.gz

WORKDIR /var/lib/yake

VOLUME ["/var/lib/yake"]

ENTRYPOINT ["/entrypoint.sh"]
