---
- name: Template vgarden files
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "/var/lib/yake/gardener-operator/{{ item }}"
    owner: "{{ gardener_operator_uid }}"
    group: "{{ gardener_operator_gid }}"
    mode: 0644
  loop:
    - rbac.yaml
    - gardenlet.yaml

- name: Create garden project and internal seed
  kubernetes.core.k8s:
    kubeconfig: /var/lib/yake/gardener-operator/kubeconfig.vgarden
    state: present
    wait: true
    src: "/var/lib/yake/gardener-operator/{{ item }}"
  loop:
    - rbac.yaml
    - gardenlet.yaml

- name: Patch gardener annotation for reconcile
  kubernetes.core.k8s:
    kubeconfig: "/var/lib/yake/kubeconfig.{{ gardener_operator_clusterapi_name }}"
    state: present
    kind: Garden
    api_version: "operator.gardener.cloud/v1alpha1"
    name: gardener
    definition:
      metadata:
        annotations:
          gardener.cloud/operation: "reconcile"
    merge_type:
      - merge

- name: Wait 100 seconds for internal seed
  ansible.builtin.pause:
    seconds: 100

- name: Template ingress-cert file
  ansible.builtin.template:
    src: seed-ingress-certificate.yaml.j2
    dest: "/var/lib/yake/gardener-operator/seed-ingress-certificate.yaml"
    owner: "{{ gardener_operator_uid }}"
    group: "{{ gardener_operator_gid }}"
    mode: 0644

- name: Create the certificate and secret
  kubernetes.core.k8s:
    kubeconfig: "/var/lib/yake/kubeconfig.{{ gardener_operator_clusterapi_name }}"
    state: present
    wait: true
    src: /var/lib/yake/gardener-operator/seed-ingress-certificate.yaml
