---
name: Build flux container image

permissions:
  packages: write

"on":
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * *"
  push:
    paths:
      - .github/workflows/build-flux-container-image.yml
      - images/flux/**
    branches:
      - main
  pull_request:
    paths:
      - .github/workflows/build-flux-container-image.yml
      - images/flux/**

jobs:
  build-flux-container-image:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        version:
          - v2.6.1  # renovate: datasource=github-releases depName=fluxcd/flux2
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Setup docker
        uses: docker/setup-buildx-action@v3

      - name: Login to container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
        if: github.repository == 'YAKEcloud/yake-ansible' && github.ref == 'refs/heads/main'

      - name: Build container image
        uses: docker/build-push-action@v6
        with:
          context: images/flux
          push: false
          tags: ghcr.io/yakecloud/flux:${{ matrix.version }}
          build-args: |
            VERSION=${{ matrix.version }}
        if: github.repository == 'YAKEcloud/yake-ansible' && github.ref != 'refs/heads/main'

      - name: Build and push container image
        uses: docker/build-push-action@v6
        with:
          context: images/flux
          push: true
          tags: ghcr.io/yakecloud/flux:${{ matrix.version }}
          build-args: |
            VERSION=${{ matrix.version }}
        if: github.repository == 'YAKEcloud/yake-ansible' && github.ref == 'refs/heads/main'
