---
name: Build kind container image

permissions:
  packages: write

"on":
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * *"
  push:
    paths:
      - .github/workflows/build-kind-container-image.yml
      - images/kind/**
    branches:
      - main
  pull_request:
    paths:
      - .github/workflows/build-kind-container-image.yml
      - images/kind/**

jobs:
  build-kind-container-image:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Setup docker
        uses: docker/setup-buildx-action@v3

      - name: Login to container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
        if: github.repository == 'YAKEcloud/yake-ansible' && github.ref == 'refs/heads/main'

      - name: Build container image
        uses: docker/build-push-action@v6
        with:
          context: images/kind
          push: false
          tags: ghcr.io/yakecloud/kind:latest
        if: github.repository == 'YAKEcloud/yake-ansible' && github.ref != 'refs/heads/main'

      - name: Build and push container image
        uses: docker/build-push-action@v6
        with:
          context: images/kind
          push: true
          tags: ghcr.io/yakecloud/kind:latest
        if: github.repository == 'YAKEcloud/yake-ansible' && github.ref == 'refs/heads/main'
